name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restart Docker
      run: sudo systemctl restart docker

    - name: Set up Minikube
      run: minikube start --driver=docker --memory=4096 --cpus=2

    - name: Set kubeconfig for Minikube
      run: |
        mkdir -p $HOME/.kube $HOME/.minikube
        touch $HOME/.kube/config
        minikube update-context

    - name: Deploy Nginx from Docker Hub
      run: |
        kubectl create deployment nginx --image=nginx
        kubectl expose deployment nginx --port=80 --type=NodePort

    - name: Get Deployments
      run: kubectl get deployments

    - name: Get Pods
      run: kubectl get pods

    - name: Wait for Nginx Pod to be ready (with retries)
      run: |
        for i in {1..5}; do
          kubectl get pods -l app=nginx && break
          echo "Waiting for Nginx Pod to be ready..."
          sleep 30
        done
        kubectl wait --for=condition=ready pod -l app=nginx --timeout=180s

    - name: Get Services
      run: kubectl get svc

    - name: Print Minikube service URL
      run: minikube service nginx --url --wait=300

