name: Deploy Nginx to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube
      run: |
        minikube start --driver=docker

    - name: Set kubeconfig for Minikube
      run: |
        mkdir -p $HOME/.kube
        touch $HOME/.kube/config
        minikube update-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services