name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube
      run: |
        minikube start --driver=docker --memory=4096 --cpus=2

    - name: Set kubeconfig for Minikube
      run: |
        mkdir -p $HOME/.kube
        touch $HOME/.kube/config
        minikube update-context

    - name: Deploy Nginx from Docker Hub
      run: |
        kubectl create deployment nginx --image=nginx
        kubectl expose deployment nginx --port=80 --type=NodePort

    - name: List all resources after deployment
      run: kubectl get all --namespace=default

    - name: Describe Nginx Deployment
      run: kubectl describe deployment nginx --namespace=default

    - name: Describe Pods
      run: kubectl describe pods -l app=nginx --namespace=default

    - name: Get Kubernetes Events
      run: kubectl get events --sort-by='.metadata.creationTimestamp' --namespace=default

    - name: Wait for Nginx Pod to be ready (with retries)
      run: |
        for i in {1..5}; do
          kubectl get pods -l app=nginx --namespace=default && break
          echo "Waiting for Nginx Pod to be ready..."
          sleep 30
        done
        kubectl wait --for=condition=ready pod -l app=nginx --timeout=180s --namespace=default

    - name: Get Services
      run: kubectl get svc --namespace=default

    - name: Print Minikube service URL
      run: minikube service nginx --url --wait=300
